// 中文简介词典。查不到时回落到包管理器给出的英文原文（见各适配器的 describe 调用）。
const ZH = {
  'homebrew/formula:ada-url': '符合 WHATWG 规范的高速 URL 解析库',
  'homebrew/formula:brotli': 'Google 开发的通用无损压缩算法',
  'homebrew/formula:c-ares': '异步 DNS 解析库',
  'homebrew/formula:ca-certificates': 'Mozilla 的根证书集合，HTTPS 验证用',
  'homebrew/formula:dav1d': 'AV1 视频解码器，主打小体积与高速度',
  'homebrew/formula:ffmpeg': '音视频的播放、录制、转码与推流工具',
  'homebrew/formula:fmt': 'C++ 的字符串格式化库',
  'homebrew/formula:gh': 'GitHub 官方命令行工具',
  'homebrew/formula:hdrhistogram_c': '高动态范围直方图库的 C 移植版，性能统计用',
  'homebrew/formula:htop': '交互式进程查看器，top 的增强版',
  'homebrew/formula:icu4c@78': 'Unicode 与国际化支持库',
  'homebrew/formula:lame': 'MP3 编码器',
  'homebrew/formula:libnghttp2': 'HTTP/2 协议的 C 语言实现',
  'homebrew/formula:libnghttp3': 'HTTP/3 协议的 C 语言实现',
  'homebrew/formula:libngtcp2': 'QUIC 协议的 C 语言实现，HTTP/3 的传输层',
  'homebrew/formula:libuv': '跨平台异步 I/O 库，Node.js 的事件循环基础',
  'homebrew/formula:libvmaf': 'Netflix 的视频画质评估算法库',
  'homebrew/formula:libvpx': 'VP8 / VP9 视频编解码器',
  'homebrew/formula:llhttp': 'Node.js 使用的 HTTP 解析器',
  'homebrew/formula:lz4': '极速压缩算法，侧重速度而非压缩率',
  'homebrew/formula:merve': '从 CommonJS 模块中提取导出名的 C++ 词法分析器',
  'homebrew/formula:mpg123': '命令行 MP3 播放器与解码库',
  'homebrew/formula:nbytes': '从 Node.js 核心抽出的字节处理函数库',
  'homebrew/formula:ncurses': '终端文本界面库，htop 这类 TUI 的基础',
  'homebrew/formula:node': 'JavaScript 运行时',
  'homebrew/formula:openssl@3': '加密与 TLS 工具包',
  'homebrew/formula:opus': '低延迟音频编解码器，语音通话常用',
  'homebrew/formula:readline': '命令行输入编辑与历史记录库',
  'homebrew/formula:sdl2-compat': '让 SDL2 程序跑在 SDL3 上的兼容层',
  'homebrew/formula:sdl3': '跨平台的音频、输入设备与图形底层访问库',
  'homebrew/formula:simdjson': '用 SIMD 指令加速的 C++ JSON 解析器',
  'homebrew/formula:simdutf': '高速 Unicode 编码转换库',
  'homebrew/formula:sqlite': '轻量级嵌入式数据库',
  'homebrew/formula:svt-av1': 'AV1 视频编码器',
  'homebrew/formula:uvwasi': '基于 libuv 实现的 WASI 系统调用层',
  'homebrew/formula:x264': 'H.264 视频编码器',
  'homebrew/formula:x265': 'H.265 / HEVC 视频编码器',
  'homebrew/formula:xz': '高压缩率的通用压缩工具',
  'homebrew/formula:zstd': 'Facebook 的实时压缩算法，速度与压缩率兼顾',

  'homebrew/cask:cc-switch': 'AI 编码助手的配置管理器',
  'homebrew/cask:claude-code': '终端里的 AI 编码助手',
  'homebrew/cask:iterm2': 'macOS 终端应用，系统自带终端的增强替代',
  'homebrew/cask:rectangle': '用快捷键或吸附区域移动和缩放窗口',

  'npm/@deepseek-ai/dsh': 'DeepSeek 的命令行工具',
  'npm/@fission-ai/openspec': '以规格驱动开发的 AI 工具',
};

export function describe(adapterId, itemId, fallback = null) {
  return ZH[`${adapterId}/${itemId}`] ?? fallback ?? null;
}
